server:
  port: 7070
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/manuelmye/Micro_Front.git
          #username:
          #password:
          search-paths: config-data
          default-label: main
  security:
    user:
      name: root
      password: s3cr3t
